name: Node CI

on:
  push:
  schedule:
    - cron: "0 15 */1 * *"

jobs:
  run:
    name: Run ebiname
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: npm install, build, and run
        run: |
          bun install
          bun run test
          bun run start
        env:
          TZ: "Asia/Tokyo"
          MASTODON_HOST: ${{ secrets.MASTODON_HOST }}
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          MASTODON_BOT_TOKEN: ${{ secrets.MASTODON_BOT_TOKEN }}
          MASTODON_NAME: ${{ secrets.MASTODON_NAME }}
